
public enum Expression
{
    DEAD,
    CUTE_PLEASE_BELIEVE_ME,
    CUTE_EVIL,
    CUTE_VV,
    FRONT_EVIL_FACE,
    FRONT_LOOK_AT_YOU,
    FRONT_NORMAL,
    CRY_RELIEF,
    HAPPY,
    NORMAL,
    NORMAL_OPEN_MOUTH,
    STRETCHING,
    SCARED_LOOK_AWAY,
    SCARED,
    WORRY,
    WORRY_OPEN_MOUTH,
    WORRY_LOOK_AWAY_OPEN_MOUTH
}